var dir_2c73685b2486fc7c13e12bff9e406598 =
[
    [ "add.hpp", "d5/d83/opencl_2prim_2add_8hpp.html", "d5/d83/opencl_2prim_2add_8hpp" ],
    [ "bernoulli_logit_glm_lpmf.hpp", "d6/dfd/opencl_2prim_2bernoulli__logit__glm__lpmf_8hpp.html", "d6/dfd/opencl_2prim_2bernoulli__logit__glm__lpmf_8hpp" ],
    [ "categorical_logit_glm_lpmf.hpp", "d5/d91/opencl_2prim_2categorical__logit__glm__lpmf_8hpp.html", "d5/d91/opencl_2prim_2categorical__logit__glm__lpmf_8hpp" ],
    [ "cholesky_decompose.hpp", "dd/d89/opencl_2prim_2cholesky__decompose_8hpp.html", "dd/d89/opencl_2prim_2cholesky__decompose_8hpp" ],
    [ "col.hpp", "d0/dc8/opencl_2prim_2col_8hpp.html", "d0/dc8/opencl_2prim_2col_8hpp" ],
    [ "cols.hpp", "db/de0/opencl_2prim_2cols_8hpp.html", "db/de0/opencl_2prim_2cols_8hpp" ],
    [ "crossprod.hpp", "d0/d4a/opencl_2prim_2crossprod_8hpp.html", "d0/d4a/opencl_2prim_2crossprod_8hpp" ],
    [ "dims.hpp", "d5/dd9/opencl_2prim_2dims_8hpp.html", "d5/dd9/opencl_2prim_2dims_8hpp" ],
    [ "divide.hpp", "d6/d89/opencl_2prim_2divide_8hpp.html", "d6/d89/opencl_2prim_2divide_8hpp" ],
    [ "divide_columns.hpp", "d2/d73/opencl_2prim_2divide__columns_8hpp.html", "d2/d73/opencl_2prim_2divide__columns_8hpp" ],
    [ "gp_exp_quad_cov.hpp", "d9/dcc/opencl_2prim_2gp__exp__quad__cov_8hpp.html", "d9/dcc/opencl_2prim_2gp__exp__quad__cov_8hpp" ],
    [ "inv.hpp", "d2/db0/opencl_2prim_2inv_8hpp.html", "d2/db0/opencl_2prim_2inv_8hpp" ],
    [ "inv_cloglog.hpp", "d7/d74/opencl_2prim_2inv__cloglog_8hpp.html", "d7/d74/opencl_2prim_2inv__cloglog_8hpp" ],
    [ "inv_sqrt.hpp", "de/d74/opencl_2prim_2inv__sqrt_8hpp.html", "de/d74/opencl_2prim_2inv__sqrt_8hpp" ],
    [ "mdivide_left_tri_low.hpp", "d6/d00/opencl_2prim_2mdivide__left__tri__low_8hpp.html", "d6/d00/opencl_2prim_2mdivide__left__tri__low_8hpp" ],
    [ "mdivide_right_tri_low.hpp", "d6/d1d/opencl_2prim_2mdivide__right__tri__low_8hpp.html", "d6/d1d/opencl_2prim_2mdivide__right__tri__low_8hpp" ],
    [ "neg_binomial_2_log_glm_lpmf.hpp", "d5/def/opencl_2prim_2neg__binomial__2__log__glm__lpmf_8hpp.html", "d5/def/opencl_2prim_2neg__binomial__2__log__glm__lpmf_8hpp" ],
    [ "normal_id_glm_lpdf.hpp", "d1/dc0/opencl_2prim_2normal__id__glm__lpdf_8hpp.html", "d1/dc0/opencl_2prim_2normal__id__glm__lpdf_8hpp" ],
    [ "ordered_logistic_glm_lpmf.hpp", "d9/dbc/opencl_2prim_2ordered__logistic__glm__lpmf_8hpp.html", "d9/dbc/opencl_2prim_2ordered__logistic__glm__lpmf_8hpp" ],
    [ "poisson_log_glm_lpmf.hpp", "dc/dbf/opencl_2prim_2poisson__log__glm__lpmf_8hpp.html", "dc/dbf/opencl_2prim_2poisson__log__glm__lpmf_8hpp" ],
    [ "rep_matrix.hpp", "da/df2/opencl_2prim_2rep__matrix_8hpp.html", "da/df2/opencl_2prim_2rep__matrix_8hpp" ],
    [ "rep_row_vector.hpp", "dd/dc5/opencl_2prim_2rep__row__vector_8hpp.html", "dd/dc5/opencl_2prim_2rep__row__vector_8hpp" ],
    [ "rep_vector.hpp", "df/dcd/opencl_2prim_2rep__vector_8hpp.html", "df/dcd/opencl_2prim_2rep__vector_8hpp" ],
    [ "row.hpp", "d8/d8f/opencl_2prim_2row_8hpp.html", "d8/d8f/opencl_2prim_2row_8hpp" ],
    [ "rows.hpp", "de/dd4/opencl_2prim_2rows_8hpp.html", "de/dd4/opencl_2prim_2rows_8hpp" ],
    [ "tcrossprod.hpp", "dd/dd8/opencl_2prim_2tcrossprod_8hpp.html", "dd/dd8/opencl_2prim_2tcrossprod_8hpp" ]
];