var searchData=
[
  ['tan_5f',['tan_',['../de/da5/classstan_1_1math_1_1tan__.html',1,'stan::math']]],
  ['tan_5ffun',['tan_fun',['../d7/d4d/structstan_1_1math_1_1tan__fun.html',1,'stan::math']]],
  ['tan_5fvari',['tan_vari',['../de/da8/classstan_1_1math_1_1internal_1_1tan__vari.html',1,'stan::math::internal']]],
  ['tanh_5f',['tanh_',['../dd/d50/classstan_1_1math_1_1tanh__.html',1,'stan::math']]],
  ['tanh_5ffun',['tanh_fun',['../db/d95/structstan_1_1math_1_1tanh__fun.html',1,'stan::math']]],
  ['tanh_5fvari',['tanh_vari',['../d8/d26/classstan_1_1math_1_1internal_1_1tanh__vari.html',1,'stan::math::internal']]],
  ['tgamma_5f',['tgamma_',['../d6/dd8/classstan_1_1math_1_1tgamma__.html',1,'stan::math']]],
  ['tgamma_5ffun',['tgamma_fun',['../df/d28/structstan_1_1math_1_1tgamma__fun.html',1,'stan::math']]],
  ['tgamma_5fvari',['tgamma_vari',['../df/de6/classstan_1_1math_1_1internal_1_1tgamma__vari.html',1,'stan::math::internal']]],
  ['to_5fbuffer',['to_buffer',['../d7/dc8/namespacestan_1_1math_1_1opencl__kernels_1_1internal.html#d8/dbe/structstan_1_1math_1_1opencl__kernels_1_1internal_1_1to__buffer',1,'stan::math::opencl_kernels::internal']]],
  ['to_5fbuffer_3c_20in_5fbuffer_20_3e',['to_buffer&lt; in_buffer &gt;',['../d7/dc8/namespacestan_1_1math_1_1opencl__kernels_1_1internal.html#dc/d77/structstan_1_1math_1_1opencl__kernels_1_1internal_1_1to__buffer_3_01in__buffer_01_4',1,'stan::math::opencl_kernels::internal']]],
  ['to_5fbuffer_3c_20in_5fout_5fbuffer_20_3e',['to_buffer&lt; in_out_buffer &gt;',['../d7/dc8/namespacestan_1_1math_1_1opencl__kernels_1_1internal.html#df/d74/structstan_1_1math_1_1opencl__kernels_1_1internal_1_1to__buffer_3_01in__out__buffer_01_4',1,'stan::math::opencl_kernels::internal']]],
  ['to_5fbuffer_3c_20out_5fbuffer_20_3e',['to_buffer&lt; out_buffer &gt;',['../d7/dc8/namespacestan_1_1math_1_1opencl__kernels_1_1internal.html#de/d7a/structstan_1_1math_1_1opencl__kernels_1_1internal_1_1to__buffer_3_01out__buffer_01_4',1,'stan::math::opencl_kernels::internal']]],
  ['trace_5fgen_5fquad_5fform_5fvari',['trace_gen_quad_form_vari',['../df/d4f/classstan_1_1math_1_1internal_1_1trace__gen__quad__form__vari.html',1,'stan::math::internal']]],
  ['trace_5fgen_5fquad_5fform_5fvari_5falloc',['trace_gen_quad_form_vari_alloc',['../db/dd1/classstan_1_1math_1_1internal_1_1trace__gen__quad__form__vari__alloc.html',1,'stan::math::internal']]],
  ['trace_5finv_5fquad_5fform_5fldlt_5fimpl',['trace_inv_quad_form_ldlt_impl',['../d7/de4/classstan_1_1math_1_1internal_1_1trace__inv__quad__form__ldlt__impl.html',1,'stan::math::internal']]],
  ['trace_5finv_5fquad_5fform_5fldlt_5fvari',['trace_inv_quad_form_ldlt_vari',['../db/d3c/classstan_1_1math_1_1internal_1_1trace__inv__quad__form__ldlt__vari.html',1,'stan::math::internal']]],
  ['trace_5fquad_5fform_5fvari',['trace_quad_form_vari',['../d8/d11/classstan_1_1math_1_1internal_1_1trace__quad__form__vari.html',1,'stan::math::internal']]],
  ['trace_5fquad_5fform_5fvari_5falloc',['trace_quad_form_vari_alloc',['../dd/d19/classstan_1_1math_1_1internal_1_1trace__quad__form__vari__alloc.html',1,'stan::math::internal']]],
  ['transpose_5f',['transpose_',['../dc/d0f/classstan_1_1math_1_1transpose__.html',1,'stan::math']]],
  ['trigamma_5ffun',['trigamma_fun',['../dd/dc0/structstan_1_1math_1_1trigamma__fun.html',1,'stan::math']]],
  ['trunc_5f',['trunc_',['../df/df1/classstan_1_1math_1_1trunc__.html',1,'stan::math']]],
  ['trunc_5ffun',['trunc_fun',['../d7/dc2/structstan_1_1math_1_1trunc__fun.html',1,'stan::math']]],
  ['trunc_5fvari',['trunc_vari',['../da/dee/classstan_1_1math_1_1internal_1_1trunc__vari.html',1,'stan::math::internal']]],
  ['tuning_5fstruct',['tuning_struct',['../de/d5f/group__opencl__context__group.html#db/d9c/structstan_1_1math_1_1opencl__context__base_1_1tuning__struct',1,'stan::math::opencl_context_base']]]
];
