var searchData=
[
  ['rank_2ehpp',['rank.hpp',['../d9/daf/rank_8hpp.html',1,'']]],
  ['rayleigh_5fccdf_5flog_2ehpp',['rayleigh_ccdf_log.hpp',['../de/d5d/rayleigh__ccdf__log_8hpp.html',1,'']]],
  ['rayleigh_5fcdf_2ehpp',['rayleigh_cdf.hpp',['../d9/d9d/rayleigh__cdf_8hpp.html',1,'']]],
  ['rayleigh_5fcdf_5flog_2ehpp',['rayleigh_cdf_log.hpp',['../d0/d87/rayleigh__cdf__log_8hpp.html',1,'']]],
  ['rayleigh_5flccdf_2ehpp',['rayleigh_lccdf.hpp',['../d1/d51/rayleigh__lccdf_8hpp.html',1,'']]],
  ['rayleigh_5flcdf_2ehpp',['rayleigh_lcdf.hpp',['../d1/de7/rayleigh__lcdf_8hpp.html',1,'']]],
  ['rayleigh_5flog_2ehpp',['rayleigh_log.hpp',['../d2/dce/rayleigh__log_8hpp.html',1,'']]],
  ['rayleigh_5flpdf_2ehpp',['rayleigh_lpdf.hpp',['../df/d51/rayleigh__lpdf_8hpp.html',1,'']]],
  ['rayleigh_5frng_2ehpp',['rayleigh_rng.hpp',['../de/dc8/rayleigh__rng_8hpp.html',1,'']]],
  ['read_5fcorr_5fl_2ehpp',['read_corr_L.hpp',['../d8/d55/read__corr___l_8hpp.html',1,'']]],
  ['read_5fcorr_5fmatrix_2ehpp',['read_corr_matrix.hpp',['../dc/dd8/read__corr__matrix_8hpp.html',1,'']]],
  ['read_5fcov_5fl_2ehpp',['read_cov_L.hpp',['../db/d0c/read__cov___l_8hpp.html',1,'']]],
  ['read_5fcov_5fmatrix_2ehpp',['read_cov_matrix.hpp',['../dd/d28/read__cov__matrix_8hpp.html',1,'']]],
  ['read_5ffvar_2ehpp',['read_fvar.hpp',['../d7/d66/read__fvar_8hpp.html',1,'']]],
  ['read_5fvar_2ehpp',['read_var.hpp',['../d3/d1b/read__var_8hpp.html',1,'']]],
  ['readme_2emd',['README.md',['../d9/dd6/_r_e_a_d_m_e_8md.html',1,'']]],
  ['real_2ehpp',['real.hpp',['../d8/d23/real_8hpp.html',1,'']]],
  ['recover_5fmemory_2ehpp',['recover_memory.hpp',['../d1/df9/recover__memory_8hpp.html',1,'']]],
  ['recover_5fmemory_5fnested_2ehpp',['recover_memory_nested.hpp',['../da/d6e/recover__memory__nested_8hpp.html',1,'']]],
  ['reduce_5fsum_2ehpp',['reduce_sum.hpp',['../d5/d99/fwd_2functor_2reduce__sum_8hpp.html',1,'(Global Namespace)'],['../d2/dfd/prim_2functor_2reduce__sum_8hpp.html',1,'(Global Namespace)'],['../db/d7a/rev_2functor_2reduce__sum_8hpp.html',1,'(Global Namespace)']]],
  ['reduce_5fsum_5fstatic_2ehpp',['reduce_sum_static.hpp',['../db/dda/reduce__sum__static_8hpp.html',1,'']]],
  ['ref_5ftype_2ehpp',['ref_type.hpp',['../d2/d08/ref__type_8hpp.html',1,'']]],
  ['rep_5farray_2ehpp',['rep_array.hpp',['../d0/dc7/rep__array_8hpp.html',1,'']]],
  ['rep_5fmatrix_2ehpp',['rep_matrix.hpp',['../d7/d6d/opencl_2kernels_2rep__matrix_8hpp.html',1,'(Global Namespace)'],['../da/df2/opencl_2prim_2rep__matrix_8hpp.html',1,'(Global Namespace)'],['../d4/d62/prim_2fun_2rep__matrix_8hpp.html',1,'(Global Namespace)']]],
  ['rep_5frow_5fvector_2ehpp',['rep_row_vector.hpp',['../dd/dc5/opencl_2prim_2rep__row__vector_8hpp.html',1,'(Global Namespace)'],['../db/d95/prim_2fun_2rep__row__vector_8hpp.html',1,'(Global Namespace)']]],
  ['rep_5fvector_2ehpp',['rep_vector.hpp',['../df/dcd/opencl_2prim_2rep__vector_8hpp.html',1,'(Global Namespace)'],['../d9/d2b/prim_2fun_2rep__vector_8hpp.html',1,'(Global Namespace)']]],
  ['require_5fgenerics_2ehpp',['require_generics.hpp',['../d0/d02/require__generics_8hpp.html',1,'']]],
  ['require_5fhelpers_2ehpp',['require_helpers.hpp',['../d2/dac/require__helpers_8hpp.html',1,'']]],
  ['resize_2ehpp',['resize.hpp',['../dc/d12/resize_8hpp.html',1,'']]],
  ['return_5ftype_2ehpp',['return_type.hpp',['../d9/d94/return__type_8hpp.html',1,'']]],
  ['rev_2ehpp',['rev.hpp',['../d4/d64/rev_8hpp.html',1,'']]],
  ['reverse_2ehpp',['reverse.hpp',['../df/d74/reverse_8hpp.html',1,'']]],
  ['rising_5ffactorial_2ehpp',['rising_factorial.hpp',['../da/dcc/fwd_2fun_2rising__factorial_8hpp.html',1,'(Global Namespace)'],['../d0/d6b/prim_2fun_2rising__factorial_8hpp.html',1,'(Global Namespace)'],['../d8/d5b/rev_2fun_2rising__factorial_8hpp.html',1,'(Global Namespace)']]],
  ['round_2ehpp',['round.hpp',['../d3/de9/fwd_2fun_2round_8hpp.html',1,'(Global Namespace)'],['../d1/dfa/prim_2fun_2round_8hpp.html',1,'(Global Namespace)'],['../d5/da9/rev_2fun_2round_8hpp.html',1,'(Global Namespace)']]],
  ['row_2ehpp',['row.hpp',['../d8/d8f/opencl_2prim_2row_8hpp.html',1,'(Global Namespace)'],['../d6/dc3/prim_2fun_2row_8hpp.html',1,'(Global Namespace)']]],
  ['rows_2ehpp',['rows.hpp',['../de/dd4/opencl_2prim_2rows_8hpp.html',1,'(Global Namespace)'],['../d9/d86/prim_2fun_2rows_8hpp.html',1,'(Global Namespace)']]],
  ['rows_5fdot_5fproduct_2ehpp',['rows_dot_product.hpp',['../d9/d21/prim_2fun_2rows__dot__product_8hpp.html',1,'(Global Namespace)'],['../d6/db4/rev_2fun_2rows__dot__product_8hpp.html',1,'(Global Namespace)']]],
  ['rows_5fdot_5fself_2ehpp',['rows_dot_self.hpp',['../d7/d75/rows__dot__self_8hpp.html',1,'']]],
  ['rowwise_5freduction_2ehpp',['rowwise_reduction.hpp',['../de/dc3/rowwise__reduction_8hpp.html',1,'']]]
];
