var searchData=
[
  ['tail_2ehpp',['tail.hpp',['../d7/d61/tail_8hpp.html',1,'']]],
  ['tan_2ehpp',['tan.hpp',['../d3/d4c/fwd_2fun_2tan_8hpp.html',1,'(Global Namespace)'],['../d3/d22/prim_2fun_2tan_8hpp.html',1,'(Global Namespace)'],['../d2/d3b/rev_2fun_2tan_8hpp.html',1,'(Global Namespace)']]],
  ['tanh_2ehpp',['tanh.hpp',['../d1/d45/fwd_2fun_2tanh_8hpp.html',1,'(Global Namespace)'],['../d2/d5c/prim_2fun_2tanh_8hpp.html',1,'(Global Namespace)'],['../d2/dce/rev_2fun_2tanh_8hpp.html',1,'(Global Namespace)']]],
  ['tcrossprod_2ehpp',['tcrossprod.hpp',['../d3/d6e/fwd_2fun_2tcrossprod_8hpp.html',1,'(Global Namespace)'],['../dd/dd8/opencl_2prim_2tcrossprod_8hpp.html',1,'(Global Namespace)'],['../d6/d23/prim_2fun_2tcrossprod_8hpp.html',1,'(Global Namespace)'],['../de/d39/rev_2fun_2tcrossprod_8hpp.html',1,'(Global Namespace)']]],
  ['tgamma_2ehpp',['tgamma.hpp',['../d5/d74/fwd_2fun_2tgamma_8hpp.html',1,'(Global Namespace)'],['../d3/d8f/prim_2fun_2tgamma_8hpp.html',1,'(Global Namespace)'],['../d6/d29/rev_2fun_2tgamma_8hpp.html',1,'(Global Namespace)']]],
  ['threading_5ftbb_2emd',['threading_tbb.md',['../d8/d53/threading__tbb_8md.html',1,'']]],
  ['throw_5fdomain_5ferror_2ehpp',['throw_domain_error.hpp',['../d2/de6/throw__domain__error_8hpp.html',1,'']]],
  ['throw_5fdomain_5ferror_5fvec_2ehpp',['throw_domain_error_vec.hpp',['../d8/dc6/throw__domain__error__vec_8hpp.html',1,'']]],
  ['to_5farray_5f1d_2ehpp',['to_array_1d.hpp',['../da/dc8/to__array__1d_8hpp.html',1,'']]],
  ['to_5farray_5f2d_2ehpp',['to_array_2d.hpp',['../dd/d5c/to__array__2d_8hpp.html',1,'']]],
  ['to_5ffvar_2ehpp',['to_fvar.hpp',['../d6/d78/to__fvar_8hpp.html',1,'']]],
  ['to_5fmatrix_2ehpp',['to_matrix.hpp',['../d8/dd6/to__matrix_8hpp.html',1,'']]],
  ['to_5fref_2ehpp',['to_ref.hpp',['../de/ddd/to__ref_8hpp.html',1,'']]],
  ['to_5frow_5fvector_2ehpp',['to_row_vector.hpp',['../d6/d36/to__row__vector_8hpp.html',1,'']]],
  ['to_5fvar_2ehpp',['to_var.hpp',['../d1/dd9/to__var_8hpp.html',1,'']]],
  ['to_5fvector_2ehpp',['to_vector.hpp',['../d5/d13/to__vector_8hpp.html',1,'']]],
  ['trace_2ehpp',['trace.hpp',['../d4/db9/trace_8hpp.html',1,'']]],
  ['trace_5fgen_5finv_5fquad_5fform_5fldlt_2ehpp',['trace_gen_inv_quad_form_ldlt.hpp',['../d2/da3/prim_2fun_2trace__gen__inv__quad__form__ldlt_8hpp.html',1,'(Global Namespace)'],['../d0/de2/rev_2fun_2trace__gen__inv__quad__form__ldlt_8hpp.html',1,'(Global Namespace)']]],
  ['trace_5fgen_5fquad_5fform_2ehpp',['trace_gen_quad_form.hpp',['../d2/d2d/prim_2fun_2trace__gen__quad__form_8hpp.html',1,'(Global Namespace)'],['../d3/d73/rev_2fun_2trace__gen__quad__form_8hpp.html',1,'(Global Namespace)']]],
  ['trace_5finv_5fquad_5fform_5fldlt_2ehpp',['trace_inv_quad_form_ldlt.hpp',['../d3/de3/prim_2fun_2trace__inv__quad__form__ldlt_8hpp.html',1,'(Global Namespace)'],['../d4/dae/rev_2fun_2trace__inv__quad__form__ldlt_8hpp.html',1,'(Global Namespace)']]],
  ['trace_5fquad_5fform_2ehpp',['trace_quad_form.hpp',['../da/d3a/fwd_2fun_2trace__quad__form_8hpp.html',1,'(Global Namespace)'],['../de/d9c/prim_2fun_2trace__quad__form_8hpp.html',1,'(Global Namespace)'],['../d9/dd4/rev_2fun_2trace__quad__form_8hpp.html',1,'(Global Namespace)']]],
  ['transpose_2ehpp',['transpose.hpp',['../d9/de7/opencl_2kernel__generator_2transpose_8hpp.html',1,'(Global Namespace)'],['../dd/d7a/prim_2fun_2transpose_8hpp.html',1,'(Global Namespace)']]],
  ['tri_5finverse_2ehpp',['tri_inverse.hpp',['../d4/dfb/tri__inverse_8hpp.html',1,'']]],
  ['triangular_5ftranspose_2ehpp',['triangular_transpose.hpp',['../dd/dc6/kernels_2triangular__transpose_8hpp.html',1,'(Global Namespace)'],['../dc/d7d/rev_2triangular__transpose_8hpp.html',1,'(Global Namespace)'],['../d2/dbd/triangular__transpose_8hpp.html',1,'(Global Namespace)']]],
  ['trigamma_2ehpp',['trigamma.hpp',['../d6/dd6/fwd_2fun_2trigamma_8hpp.html',1,'(Global Namespace)'],['../d5/d0c/prim_2fun_2trigamma_8hpp.html',1,'(Global Namespace)'],['../d0/dca/rev_2fun_2trigamma_8hpp.html',1,'(Global Namespace)']]],
  ['trunc_2ehpp',['trunc.hpp',['../d3/d10/fwd_2fun_2trunc_8hpp.html',1,'(Global Namespace)'],['../d0/d91/prim_2fun_2trunc_8hpp.html',1,'(Global Namespace)'],['../d5/dcb/rev_2fun_2trunc_8hpp.html',1,'(Global Namespace)']]],
  ['type_5fstr_2ehpp',['type_str.hpp',['../d6/d6c/type__str_8hpp.html',1,'']]],
  ['typedefs_2ehpp',['typedefs.hpp',['../d2/d80/fwd_2fun_2typedefs_8hpp.html',1,'(Global Namespace)'],['../dd/d5f/mix_2fun_2typedefs_8hpp.html',1,'(Global Namespace)'],['../d1/d29/prim_2fun_2typedefs_8hpp.html',1,'(Global Namespace)'],['../df/d8e/rev_2fun_2typedefs_8hpp.html',1,'(Global Namespace)']]]
];
